#!/bin/bash -ev

mvn clean package -DskipTests -Dtargetbinary=benchmark
mvn install dependency:copy-dependencies -Dtargetbinary=benchmark
cp -f target/benchmark.jar ./benchmark-bin
rsync -avh target/dependency/* ./benchmark-bin --delete

cd ./benchmark-bin

java -jar benchmark.jar -rf latex
