#!/bin/bash -ev

rm -fr bin

mkdir bin

mvn clean package -DskipTests
mvn install dependency:copy-dependencies

cp -f target/dht-observer.jar ./bin
rsync -avh target/dependency/* ./bin --delete

mvn clean package -DskipTests -Dtargetbinary=dhtgetpeers
cp -f target/dht-get-peers.jar ./bin

cd ./bin

cdate=$(date +"%Y-%m-%d-%H-%M-%S")

java -XX:+FlightRecorder \
 -XX:StartFlightRecording=maxsize=0,maxage=0,disk=true,dumponexit=true,name=dht-observer-$cdate,filename=dht-observer-$cdate.jfr \
 -jar dht-observer.jar $*