spring :
  application :
    name : DhtObserver
  main :
    web-application-type : NONE

geoDb:
  csvPath : "/storage/db/geo/maxmind/2010-10.MaxMind GeoIP City CSV Format/GeoIP-139_20101001/GeoIPCity.utf-8.csv"

