#!/bin/bash -ev

mvn clean package -DskipTests
mvn install dependency:copy-dependencies

mkdir bin
cp -f target/dht-observer.jar ./bin
rsync -avh target/dependency/* ./bin --delete

mvn clean package -DskipTests -Dtargetbinary=dhtgetpeers
cp -f target/dht-get-peers.jar ./bin
