application :
  peer_id : "8573195880de48268c84cd58bcc5a19b"
  listeners:
    # 16680 49001 43567 4665 4672 51413 46434 48529
    - { port : 16680, shortCode : "VZ1" }
    - { port : 49001, shortCode : "VZ2" }
    - { port : 43567, shortCode : "VZ3" }

    - { port : 4665,  shortCode : "AM1" }
    - { port : 4672,  shortCode : "AM2" }

    - { port : 51413, shortCode : "TR1" }
    - { port : 46434, shortCode : "TR2" }
    - { port : 48529, shortCode : "TR3" }

geoDb:
  csvPath : "/dev/null"

ipFilterEmule:
  guardingPath : "/bigdata/db/emule/guarding.p2p"




